/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "hsl(var(--bg))",
        surface: "hsl(var(--surface))",
        "surface-solid": "hsl(var(--surface-solid))",
        "surface-hover": "hsl(var(--hover))",
        "surface-selected": "hsl(var(--selected))",
        stroke: "hsl(var(--stroke))",
        "text-1": "hsl(var(--text))",
        "text-2": "hsl(var(--text-2))",
        "text-3": "hsl(var(--text-3))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        overlay: "hsl(var(--overlay))",
        "overlay-heavy": "hsl(var(--overlay-heavy))",
        "switch-knob": "hsl(var(--switch-knob))",
        "status-success": {
          DEFAULT: "hsl(var(--status-success))",
          foreground: "hsl(var(--status-success-foreground))",
          muted: "hsl(var(--status-success-muted))",
        },
        "status-warning": {
          DEFAULT: "hsl(var(--status-warning))",
          foreground: "hsl(var(--status-warning-foreground))",
          muted: "hsl(var(--status-warning-muted))",
        },
        "status-error": {
          DEFAULT: "hsl(var(--status-error))",
          foreground: "hsl(var(--status-error-foreground))",
          muted: "hsl(var(--status-error-muted))",
        },
        "status-info": {
          DEFAULT: "hsl(var(--status-info))",
          foreground: "hsl(var(--status-info-foreground))",
          muted: "hsl(var(--status-info-muted))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      borderRadius: {
        "4xl": "var(--radius-4xl)",
        "3xl": "var(--radius-3xl)",
        "2xl": "var(--radius-2xl)",
        xl: "var(--radius-xl)",
        lg: "var(--radius-lg)",
        md: "var(--radius-md)",
        sm: "var(--radius-sm)",
        xs: "var(--radius-xs)",
        "2xs": "var(--radius-2xs)",
      },
      fontSize: {
        xs: ["var(--text-xs)", { lineHeight: "var(--text-xs--line-height, 1.33)" }],
        sm: ["var(--text-sm)", { lineHeight: "var(--text-sm--line-height, 1.43)" }],
        base: ["var(--text-base)", { lineHeight: "var(--text-base--line-height, 1.5)" }],
        lg: ["var(--text-lg)", { lineHeight: "var(--text-lg--line-height, 1.56)" }],
        xl: ["var(--text-xl)", { lineHeight: "var(--text-xl--line-height, 1.4)" }],
        "2xl": ["var(--text-2xl)", { lineHeight: "var(--text-2xl--line-height, 1.33)" }],
        "3xl": ["var(--text-3xl)", { lineHeight: "var(--text-3xl--line-height, 1.2)" }],
        "4xl": ["var(--text-4xl)", { lineHeight: "1" }],
        "heading-lg": ["var(--text-heading-lg)", { lineHeight: "1.3" }],
        "heading-md": ["var(--text-heading-md)", { lineHeight: "1.4" }],
      },
      fontWeight: {
        light: "var(--font-weight-light)",
        normal: "var(--font-weight-normal)",
        medium: "var(--font-weight-medium)",
        semibold: "var(--font-weight-semibold)",
        bold: "var(--font-weight-bold)",
      },
      fontFamily: {
        sans: "var(--font-sans)",
        mono: "var(--font-mono)",
      },
      letterSpacing: {
        tight: "var(--tracking-tight)",
        normal: "var(--tracking-normal)",
        wide: "var(--tracking-wide)",
      },
      lineHeight: {
        tight: "var(--leading-tight)",
        normal: "var(--leading-normal)",
        relaxed: "var(--leading-relaxed)",
      },
      spacing: {
        "toolbar": "var(--height-toolbar)",
        "toolbar-sm": "var(--height-toolbar-sm)",
        "panel": "var(--padding-panel)",
        "row-x": "var(--padding-row-x)",
        "row-y": "var(--padding-row-y)",
        "sidebar": "var(--spacing-token-sidebar)",
      },
      maxWidth: {
        "thread-composer": "var(--thread-composer-max-width)",
        "thread-content": "var(--thread-content-max-width)",
        "container-3xs": "var(--container-3xs)",
        "container-xs": "var(--container-xs)",
        "container-sm": "var(--container-sm)",
        "container-md": "var(--container-md)",
        "container-lg": "var(--container-lg)",
        "container-xl": "var(--container-xl)",
        "container-2xl": "var(--container-2xl)",
        "container-3xl": "var(--container-3xl)",
      },
      height: {
        toolbar: "var(--height-toolbar)",
        "toolbar-sm": "var(--height-toolbar-sm)",
      },
      width: {
        sidebar: "var(--spacing-token-sidebar)",
      },
      zIndex: {
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        modal: "var(--z-modal)",
        popover: "var(--z-popover)",
        tooltip: "var(--z-tooltip)",
        toast: "var(--z-toast)",
        overlay: "var(--z-overlay)",
      },
      boxShadow: {
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
      },
      blur: {
        sm: "var(--blur-sm)",
        md: "var(--blur-md)",
        lg: "var(--blur-lg)",
        xl: "var(--blur-xl)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
        slower: "var(--duration-slower)",
        relaxed: "var(--transition-duration-relaxed)",
      },
      transitionTimingFunction: {
        "ease-out": "var(--ease-out)",
        "ease-in-out": "var(--ease-in-out)",
        "ease-spring": "var(--ease-spring)",
        "cubic-enter": "var(--cubic-enter)",
        DEFAULT: "var(--default-transition-timing-function)",
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slide-in-bottom": {
          from: { transform: "translateY(16px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        "slide-in-right": {
          from: { transform: "translateX(100%)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "zoom-in": {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        spin: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "accordion-open": {
          from: { height: "0", opacity: "0" },
          to: { height: "var(--accordion-content-height, auto)", opacity: "1" },
        },
        "accordion-close": {
          from: { height: "var(--accordion-content-height, auto)", opacity: "1" },
          to: { height: "0", opacity: "0" },
        },
      },
      animation: {
        "fade-in": "fade-in var(--duration-normal) var(--ease-out)",
        "slide-in-bottom": "slide-in-bottom var(--duration-normal) var(--ease-out)",
        "slide-in-right": "slide-in-right var(--duration-normal) var(--ease-out)",
        "zoom-in": "zoom-in var(--duration-normal) var(--ease-out)",
        spin: "spin 1s linear infinite",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "accordion-open": "accordion-open var(--duration-normal) var(--ease-out)",
        "accordion-close": "accordion-close var(--duration-fast) var(--ease-in-out)",
      },
    },
  },
  plugins: [],
}
